### ISSUE TITLE
please balance to ftb standards

### ISSUE THREAD

**Issue by ChloeDawn** [TehNut-Mods/NuclearCubes#6]
this mod needs more balance, i suggest some clay

**Comment by TehNut** [comment]
will do. nukes will run on clay and generate pwoer based one the quality if the clya. also the structure has to be encased in clay to run . ocasionaly a wierd clay wil be produced and you wil have to proces it to get more clay from it

**Comment by TheIcyOne** [comment]
But how do you break the clay?

**Comment by TehNut** [comment]
you don't

**Comment by ChloeDawn** [comment]
1.11.2 when

**Comment by ghost** [comment]
you do with a clay shovel made from clay

**Comment by TheIcyOne** [comment]
That sounds balanced.

**Comment by ghost** [comment]
thx nut

**Comment by TheIcyOne** [comment]
:(
